title = "Library of Alexandria"
# logo = "img/logo.jpg"
# copyright = "Copy, _right?_ :thinking_face:"

[languages]
  [languages.en]
    [languages.en.params]
      dateFormat = "2 January 2006"
      description = "Project portfolio and blog"
      languageName = "English"
      displayName = "EN"
      isoCode = "en"
      weight = 1
      rtl = false

[author]
  image = "img/author.jpg"
  headline = "Aspiring software engineer with a boundless curiosity."
  links = [
    { email = "mailto:alexander@alexandersauceda.dev" },
    { github = "https://github.com/alesauce" },
    { linkedin = "https://www.linkedin.com/in/alexander-matthew-sauceda/" },
    { stack-overflow = "https://stackoverflow.com/users/19834001/alesauce" },
  ]
